/**
 * Central Window bridge typings for the Orbis JS→TS migration.
 * Module files assign handlers to window.*; do not re-declare Window per module.
 */
import type { SupabaseClient } from '@supabase/supabase-js';
import type { HrIntelligenceContext } from '../services/hrIntelligence';
import type { HrInboxItem } from '../services/hrInbox';

export {};

declare global {
  interface Window {
    __orbisMainBoot?: boolean;
    __orbisBootComplete?: boolean;
    loadEmployees?: () => Promise<unknown>;
    syncOpenedEmployeeRecordId?: (employeeId: string) => void;
    cleanEmployeeFormNameValue?: (value: unknown) => string;
    getEmployeeFormData?: () => Record<string, unknown>;
    populateEmployeeForm?: (employee: Record<string, unknown>) => void;
    resetEmployeeForm?: () => void;
    saveEmployeeForm?: () => Promise<void>;
    saveEmployeeRecord?: () => Promise<void>;
    openCommandPalette?: () => void;
    closeCommandPalette?: () => void;
    currentEmployee?: Record<string, unknown> | null;
    loadEmployeeHistory?: (employeeId: string) => void | Promise<void>;
    getResolvedHistoryEmployeeId?: (employeeId?: string | null) => string;
    renderHistoryList?: ( containerId: string, records: Record<string, unknown>[], emptyMessage?: string ) => void;
    appendHistoryItem?: (containerId: string, record: Record<string, unknown>) => void;
    clearHistoryList?: (containerId: string, emptyMessage?: string) => void;
    getAuditTrail?: () => Record<string, unknown>[];
    getOrCreateDashboardSectionBody?: (title: string, id: string) => HTMLElement | null;
    initAccessibleDrawerTabs?: () => void;
    activateDrawerTab?: (kind: string, tabName: string, focusTab?: boolean) => boolean | void;
    ensureDrawerLayout?: (...args: unknown[]) => unknown;
    setEmployeeDrawerCreateMode?: (...args: unknown[]) => unknown;
    populateDepartmentFilter?: () => void;
    renderDepartmentSummary?: () => void;
    __hrInboxCache?: HrInboxItem[];
    loadHrInbox?: (force?: boolean) => Promise<void>;
    applyHrInboxAccess?: () => void;
    getHrInboxItems?: () => HrInboxItem[];
    openCandidatesView?: () => void;
    openEmployeesView?: () => void;
    openDashboardView?: () => void;
    switchMainView?: (sectionId: string) => void;
    currentMainView?: string;
    getEmployeeMapKeys?: (employee: Record<string, unknown>) => string[];
    getEmployeeRiskMeta?: (employee: Record<string, unknown>) => Record<string, unknown> | null;
    getEmployeeImpactMeta?: (employee: Record<string, unknown>) => Record<string, unknown> | null;
    isEmployeeAtRisk?: (employee: Record<string, unknown>) => boolean;
    isEmployeeImpactPlayer?: (employee: Record<string, unknown>) => boolean;
    hasActiveRiskMeta?: (meta: Record<string, unknown> | null | undefined) => boolean;
    hasActiveImpactMeta?: (meta: Record<string, unknown> | null | undefined) => boolean;
    buildRiskBadgeHtml?: (meta: Record<string, unknown> | null) => string;
    buildImpactBadgeHtml?: (meta: Record<string, unknown> | null) => string;
    updateEmployeeRowBadges?: () => void;
    EMPLOYEES?: Record<string, unknown>[];
    isCreatingEmployee?: boolean;
    safeGet?: (id: string) => HTMLElement | null;
    esc?: (value: unknown) => string;
    switchTab?: (tabName: string) => void;
    setText?: (id: string, value: unknown) => void;
    resetDrawerForms?: () => void;
    setCurrentEmployeeForOrbis?: (employee: Record<string, unknown> | null) => void;
    ensureDeleteEmployeeButton?: () => void | HTMLButtonElement | null;
    runTerminateEmployee?: () => void | Promise<void>;
    applyRolePermissions?: () => void;
    loadEmployeeNotes?: (employeeId: string) => void;
    loadEmployeeDiscipline?: (employeeId: string) => void | Promise<void>;
    loadEmployeeMeetings?: (employeeId: string) => void | Promise<void>;
    loadEmergencyContacts?: (employeeId: string) => void | Promise<void>;
    loadEmployeeDocuments?: (employeeId: string) => void | Promise<void>;
    loadEmployeeReviews?: (employeeId: string) => void | Promise<void>;
    loadEmployeeIncidents?: (employeeId: string) => void | Promise<void>;
    loadStayInterviews?: (employeeId: string) => void | Promise<void>;
    loadEmployeeOnboarding?: (employeeId: string) => void;
    loadEmployeeManualAtRisk?: (employeeId: string) => void | Promise<void>;
    loadEmployeeManualImpactPlayer?: (employeeId: string) => void | Promise<void>;
    markEmployeeAtRisk?: () => void | Promise<void>;
    clearAtRiskStatus?: () => void | Promise<void>;
    markImpactPlayer?: () => void | Promise<void>;
    clearImpactPlayerStatus?: () => void | Promise<void>;
    openDrawer?: (employee: Record<string, unknown>) => void;
    closeDrawer?: () => void;
    switchDrawerTab?: (tabName: string) => void;
    bindDrawerEvents?: () => void;
    forcePopulateEmployeeAdminPanel?: (employee: DrawerUiEmployee | null | undefined) => void;
    drawerEscapeKeyBound?: boolean;
    drawerFocusTrapBound?: boolean;
    getResolvedDrawerEmployeeId?: (employee?: DrawerUiEmployee | null) => string | null;
    getDrawerHeaderEmployeeId?: () => string;
    formatDrawerDateForDisplay?: (value: unknown) => string;
    getNextUpcomingAnniversaryDate?: (value: unknown) => string;
    updateWorkspaceAlerts?: () => void;
    hrIntelligenceContext?: HrIntelligenceContext;
    loadExecutiveInsight?: () => void;
    buildExecutiveInsightFromState?: typeof buildExecutiveInsightFromState;
    loadAllDashboardData?: () => Promise<void>;
    updateDashboardSyncStatus?: ( status: DashboardSyncStatus, syncedAt?: Date ) => void;
    showRosterTableSkeleton?: (rowCount?: number) => void;
    showKpiGridLoading?: () => void;
    hideKpiGridLoading?: () => void;
    showDashboardLoadingSkeletons?: () => void;
    hideDashboardLoadingSkeletons?: () => void;
    showOrbisConfirm?: typeof showOrbisConfirm;
    initOrbisDisclosure?: typeof initOrbisDisclosure;
    initDashboardDisclosure?: typeof initDashboardDisclosure;
    renderEmployeeDrawerRiskSignals?: typeof renderEmployeeDrawerRiskSignals;
    refreshEmployeeDrawerRiskSignalsIfOpen?: typeof refreshEmployeeDrawerRiskSignalsIfOpen;
    clearEmployeeDrawerRiskSignals?: typeof clearEmployeeDrawerRiskSignals;
    ALL_EMPLOYEES?: Record<string, unknown>[];
    currentEmployeeRoster?: Record<string, unknown>[];
    renderBasicDashboardKpis?: (employees?: Record<string, unknown>[]) => void;
    flushRenderBasicDashboardKpis?: () => void;
    refreshDashboardKpis?: (employees?: KpiEmployeeRecord[]) => void;
    renderKpiEmployeeMetrics?: () => void;
    refreshTurnoverKpisFromSupabase?: () => Promise<void>;
    buildKpiHoverDetails?: () => void;
    initKpiHoverUi?: () => void;
    syncKpiCardTooltip?: (card: Element | null, text: string) => void;
    updateTurnoverRiskKpi?: (rate: number, subtext: string) => void;
    currentImpactPlayerRosterMap?: Record<string, unknown>;
    currentAtRiskRosterMap?: Record<string, unknown>;
    loadSummaryMetrics?: () => Promise<void>;
    compareText?: (a: unknown, b: unknown) => number;
    safeSet?: (id: string, value: unknown) => void;
    clearSig?: (canvasId: string, statusId: string) => void;
    initDisciplineSignaturePads?: () => void;
    initIncidentSignaturePads?: () => void;
    initReviewSignaturePads?: () => void;
    scrubAllSignatureNameInputs?: () => void;
    setSignatureRequestContext?: (context: SignatureRequestContext | null) => void;
    requestEmployeeSignatureLink?: ( formType: SignatureFormType, recordId: string, employeeId: string, signerName?: string, signerEmail?: string ) => Promise<void>;
    showAppSection?: (sectionId: string) => void;
    ensureInvestigationsLoaded?: (force?: boolean) => void;
    ensureInvestigationsReady?: () => Promise<void>;
    loadInvestigations?: () => Promise<void>;
    ensureCareEngagementLoaded?: (force?: boolean) => void;
    loadCareEngagement?: () => Promise<void>;
    loadAttendance?: (force?: boolean) => Promise<void>;
    loadOrgChart?: () => Promise<void>;
    renderOrgChart?: () => void;
    loadMyProfilePortal?: () => Promise<void>;
    loadMyTasksPortal?: () => Promise<void>;
    loadMyHandbookPortal?: () => Promise<void>;
    loadMyDirectoryPortal?: () => Promise<void>;
    loadMyTimeOffPortal?: () => Promise<void>;
    loadInternalJobBoard?: (force?: boolean) => Promise<void>;
    ensureInternalJobBoardLoaded?: (force?: boolean) => void;
    openInternalJobBoardView?: (postingId?: string, tab?: 'openings' | 'manage' | 'pipeline') => void;
    loadEmployeeInternalJobInterests?: (employeeId: string) => Promise<void>;
    loadMobileActivityFeed?: (force?: boolean) => Promise<void>;
    loadJanus?: (force?: boolean) => Promise<void>;
    renderDashboardCharts?: (employees?: Record<string, unknown>[]) => void;
    mountDrawerIdentityHeader?: typeof mountDrawerIdentityHeader;
    mountLegacyDrawerHeader?: typeof mountLegacyDrawerHeader;
    hideDrawerLegacyHeader?: typeof hideDrawerLegacyHeader;
    restoreDrawerLegacyHeader?: typeof restoreDrawerLegacyHeader;
    removeDrawerIdentityHeader?: typeof removeDrawerIdentityHeader;
    restoreDrawerTabPlacement?: typeof restoreDrawerTabPlacement;
    SpeechRecognition?: typeof SpeechRecognition;
    webkitSpeechRecognition?: typeof SpeechRecognition;
    currentManualAtRiskState?: { flagged: boolean; reason: string };
    currentManualImpactPlayerState?: { flagged: boolean; reason: string };
    sanitizeDisciplineAutofillLeak?: (forceClear?: boolean) => void;
    getCurrentEmployeeForOrbis?: () => Record<string, unknown> | null;
    ensureDrawerTabFallbacks?: (employee?: Record<string, unknown> | null) => void;
    currentSort?: { column: string; direction: string };
    renderRoster?: () => void;
    renderEmployeeRoster?: () => void;
    initCommandPalette?: () => void;
    setHTML?: (id: string, value: unknown) => void;
    nl2br?: (value: unknown) => string;
    fmtDate?: (value: unknown) => string;
    fmtDateTime?: (value: unknown) => string;
    toInputDate?: (value: unknown) => string;
    todayInputValue?: () => string;
    getCurrentEmployeeDisplayName?: () => string;
    getCurrentEmployeeDisplayId?: () => string;
    statusBadge?: (status: unknown) => string;
    showToast?: (message: string, type?: string) => void;
    printField?: (label: string, value: string) => string;
    printEmployeeInfo?: (extraFieldsHTML?: string) => string;
    printSection?: (title: string, contentHTML: string) => string;
    printRecord?: (title: string, contentHTML: string) => void;
    printNote?: () => void;
    printDiscipline?: () => void;
    printDisciplineRecord?: (record: {
      incident_date?: string;
      issue_type?: string;
      discipline_level?: string;
      report_status?: string;
      description?: string;
      action_taken?: string;
      refused_to_sign?: boolean;
      employee_signature?: string;
      manager_signature?: string;
      witness_signature?: string;
    }) => void;
    printIncident?: () => void;
    printStayInterview?: () => void;
    printMeeting?: () => void;
    printReview?: () => void;
    canAccessPerformanceReviews?: (employee?: EmployeeLike | null) => boolean;
    canAccessDisciplineForEmployee?: (employee?: EmployeeLike | null) => boolean;
    canViewDisciplineReports?: () => boolean;
    hasOrgWideDisciplineAccess?: () => boolean;
    refreshMobileTasksBadge?: () => Promise<void>;
    getFilteredRosterEmployees?: () => RosterEmployee[];
    currentFilteredEmployees?: Record<string, unknown>[];
    renderMobileEmployeeRoster?: () => void;
    openDrawerByEmployeeId?: (id: string) => Promise<void>;
    openEmployeeDrawer?: (id: string) => Promise<void>;
    refreshMobileTasksUi?: () => Promise<void>;
    openInvestigationDrawer?: (id: string) => Promise<void>;
    openOperationsIssueDrawer?: (id: string) => Promise<void>;
    refreshMobilePortalUi?: () => void;
    closeActiveDrawer?: () => void;
    renderMobileStayInterviewCards?: (rows: StayInterviewMobileRow[]) => void;
    renderMobileOperationsCards?: (issues: OperationsIssue[]) => void;
    renderMobileInvestigationCards?: (rows: Investigation[]) => void;
    renderMobileCareCards?: (items: CareTrackerItem[]) => void;
    renderMobileCandidateCards?: (rows: CandidateRow[]) => void;
    renderMobileAttendanceRollCall?: (rows: AttendanceRollRow[]) => void;
    renderMobileAbsenceCards?: (rows: AbsenceRow[]) => void;
    renderMobileOrgChartDrill?: () => void;
    renderMobileSettingsNav?: () => void;
    refreshMobileNavigation?: () => void;
    initStayInterviewOrgInsights?: () => void;
    currentCandidateId?: string | null;
    currentCandidateNoteId?: string | null;
    switchCandidateTab?: (tabName: string) => void;
    loadCandidateNotes?: (candidateId?: string) => Promise<void>;
    saveCandidateNote?: () => Promise<void>;
    deleteCandidateNote?: (noteId: string) => Promise<void>;
    startCandidateNoteEdit?: (note: CandidateNote) => void;
    cancelCandidateNoteEdit?: () => void;
    saveMyProfileContactInfo?: () => Promise<void>;
    saveMyEmergencyContactPortal?: () => Promise<void>;
    deleteMyEmergencyContactPortal?: () => Promise<void>;
    resetMyEmergencyContactForm?: () => void;
    populateEmployeeAdminForm?: (employee: Record<string, unknown>) => void;
    updateEmployeeById?: ( employeeId: string, payload: Record<string, unknown> ) => Promise<{ data: Record<string, unknown> | null; error: Error | null }>;
    deleteEmployeeById?: (employeeId: string) => Promise<{ error: Error | null }>;
    runDeleteEmployee?: () => void | Promise<void>;
    openNewEmployeeForm?: () => void;
    openNewEmployeeDrawer?: () => void;
    ensureEmployeeDrawerVisible?: () => void;
    updateReviewsDueKpi?: (count: number) => void;
    clearEmployeeAdminForm?: () => void;
    createEmployee?: () => void;
    sanitizeVisibleEmployeeNameFields?: () => void;
    renderEmployeeDrawerIdentityHeader?: (employee: Record<string, unknown> | null | undefined) => void;
    syncEmployeeTerminationDateFieldVisibility?: (status?: unknown) => void;
    updateBenefitsEligibilityHint?: (employee?: Record<string, unknown> | null) => void;
    currentIncidentId?: string | null;
    loadIncidentReports?: (employeeId: string) => Promise<void>;
    loadEmployeeIncidentReports?: (employeeId: string) => Promise<void>;
    saveIncidentRecord?: () => Promise<void>;
    saveIncidentReport?: () => Promise<void>;
    editIncidentRecord?: (record: IncidentRecord) => void;
    deleteIncidentRecord?: (recordId: string, employeeId: string) => Promise<void>;
    currentStayInterviewId?: string | null;
    saveStayInterview?: () => Promise<void>;
    editStayInterview?: (stayInterviewId: string) => Promise<void>;
    deleteStayInterview?: (stayInterviewId: string) => Promise<void>;
    cancelStayInterviewEdit?: () => void;
    generateStayInterviewSummary?: () => Promise<void>;
    exportInvestigationsCsv?: () => void;
    openInvestigationsView?: () => void;
    openNewInvestigationForm?: () => void;
    closeInvestigationDrawer?: () => void;
    saveInvestigationRecord?: () => Promise<void>;
    deleteInvestigationRecord?: () => Promise<void>;
    deleteInvestigationById?: (investigationId: string) => Promise<void>;
    cancelInvestigationEdit?: () => void;
    isInvestigationDrawerOpen?: () => boolean;
    applyInvestigationsCenterAccess?: () => void;
    generateInvestigationGuidance?: () => Promise<void>;
    loadCandidates?: () => Promise<void>;
    saveCandidateRecord?: () => Promise<void>;
    saveCandidate?: () => Promise<void>;
    saveCandidateProfile?: () => Promise<void>;
    editCandidateRecord?: (record: CandidateRecord) => void;
    deleteCandidateRecord?: (candidateId?: string) => Promise<void>;
    moveCandidateToStage?: (candidateId: string, newStage: string) => Promise<void>;
    convertCandidateToEmployee?: (candidateId: string) => Promise<boolean | void>;
    convertCurrentCandidateToEmployee?: () => Promise<void>;
    refreshCandidatesView?: () => Promise<void>;
    openCandidateDrawer?: (candidateId: string) => Promise<void>;
    closeCandidateDrawer?: () => void;
    isCandidateDrawerOpen?: () => boolean;
    closeEmployeeDrawer?: () => void;
    openNewCandidateForm?: () => void;
    createCandidateFromEmployee?: () => Promise<void>;
    inviteCandidateToInterview?: () => void;
    emailCandidateSummaryToLeadership?: () => Promise<void>;
    loadManagerHome?: (force?: boolean) => Promise<void>;
    applyManagerHomeAccess?: () => void;
    applyCareEngagementCenterAccess?: () => void;
    openCareEngagementView?: () => void;
    getCareEngagementDataset?: () => CareEngagementDataset | null;
    loadEmployeeCareSupport?: (employeeId: string) => Promise<void>;
    invalidateEmployeeCareSupportCache?: () => void;
    loadDashboardOverview?: () => Promise<void>;
    refreshOrbisWorkspace?: () => Promise<void>;
    loadReviewDashboardFallback?: () => Promise<void>;
    loadReviewDashboard?: () => Promise<void>;
    loadExecutiveInsightFallback?: () => Promise<void>;
    loadRiskEmployeesFallback?: () => Promise<void>;
    loadImpactPlayersFallback?: () => Promise<void>;
    cleanReviewDashboardLooseCount?: () => void;
    buildRiskPreview?: () => void;
    loadPolicyCampaignsAdmin?: () => Promise<void>;
    getEmployeeAdminPanel?: () => HTMLElement | null;
    resetDrawerEntryForms?: () => void;
    resetEmergencyContactForm?: () => void;
    currentDisciplineReportId?: string | null;
    currentNoteId?: string | null;
    currentMeetingId?: string | null;
    currentReviewId?: string | null;
    currentIncidentReportId?: string | null;
    reviewAttachmentContextId?: string | null;
    openErSigningModal?: (token: string) => Promise<void>;
    queueEmployeeSignatureAndOpenPdf?: typeof queueEmployeeSignatureAndOpenPdf;
    bootErSigningFromUrl?: () => void;
    loadReportsSection?: (force?: boolean) => Promise<void>;
    exportReportsStayInterviewsCsv?: () => void;
    exportReportsHeadcountCsv?: () => void;
    exportReportsErTrendsCsv?: () => void;
    printReportsSection?: () => void;
    openJanusAccountDrawer?: (accountId?: string, tab?: string) => Promise<void>;
    closeJanusAccountDrawer?: () => void;
    saveJanusAccountRecord?: () => Promise<void>;
    isJanusAccountDrawerOpen?: () => boolean;
    applyJanusDrawerAccess?: () => void;
    loadOperationsIssues?: () => Promise<void>;
    ensureOperationsIssuesLoaded?: (force?: boolean) => void;
    exportOperationsIssuesCsv?: () => void;
    openOperationsView?: () => void;
    openNewOperationsIssueForm?: () => void;
    closeOperationsIssueDrawer?: () => void;
    saveOperationsIssueRecord?: () => Promise<void>;
    deleteOperationsIssueRecord?: () => Promise<void>;
    deleteOperationsIssueById?: (issueId: string) => Promise<void>;
    cancelOperationsIssueEdit?: () => void;
    isOperationsIssueDrawerOpen?: () => boolean;
    applyOperationsCenterAccess?: () => void;
    resetEmployeeDrawerTabLoadState?: () => void;
    invalidateEmployeeDrawerTab?: (tabName: string) => void;
    loadEmployeeDrawerTab?: (tabName: string, employeeId?: string) => void;
    loadOnboardingTasks?: (employeeId: string) => Promise<void>;
    loadOffboardingTasks?: (employeeId: string) => Promise<void>;
    loadEmployeePayrollHandoffs?: (employeeId: string) => Promise<void>;
    closeCareEngagementDrawer?: () => void;
    loadRecentActivity?: () => Promise<void>;
    getResolvedNoteEmployeeId?: (employeeId?: string | null) => string;
    startNoteEdit?: (note: EmployeeNote) => void;
    cancelNoteEdit?: () => void;
    saveEmployeeNote?: () => Promise<void>;
    deleteNote?: (noteId: string) => Promise<void>;
    submitMyTimeOffRequest?: () => Promise<void>;
    acknowledgeHandbookFromPortal?: (documentId: string) => Promise<void>;
    acknowledgePolicyFromPortal?: (assignmentId: string, documentId?: string) => Promise<void>;
    supabase?: SupabaseClient;
    supabaseClient?: SupabaseClient;
    getOrbisSupabaseClient?: () => any;
    initializeDocumentsLibrary?: () => void;
    orbisSupabase?: any;
    db?: any;
    currentEmergencyContactId?: string | null;
    saveEmergencyContact?: () => Promise<void>;
    deleteEmergencyContact?: () => Promise<void>;
    setEmergencyContactPriority?: (contactId: string, rank: number) => Promise<void>;
    loadEmployeeLeaveRequests?: (employeeId: string) => Promise<void>;
    submitEmployeeLeaveRequest?: () => Promise<void>;
    approveLeaveRequestById?: (requestId: string) => Promise<void>;
    denyLeaveRequestById?: (requestId: string) => Promise<void>;
    cancelLeaveRequestById?: (requestId: string) => Promise<void>;
    applyLeaveAccess?: () => void;
    toggleOnboardingTask?: (taskId: string, isComplete: boolean) => Promise<void>;
    updateOnboardingTaskField?: ( taskId: string, patch: Partial<Pick<OnboardingTaskRecord, 'due_date' | 'assigned_to' | 'show_in_portal'>> ) => Promise<void>;
    createDefaultOnboardingTasks?: (employeeId: string) => Promise<void>;
    loadMeetingRecords?: (employeeId: string) => Promise<void>;
    saveMeetingRecord?: () => Promise<void>;
    saveMeeting?: () => Promise<void>;
    editMeetingRecord?: (record: MeetingRecord) => void;
    deleteMeetingRecord?: (recordId: string, employeeId: string) => Promise<void>;
    cancelMeetingEdit?: () => void;
    applyAttendanceAccess?: () => void;
    loadSettingsAdmin?: (force?: boolean) => Promise<void>;
    currentDisciplineId?: string | null;
    saveDisciplineRecord?: () => Promise<void>;
    saveDisciplineReport?: () => Promise<void>;
    editDisciplineRecord?: (record: DisciplineRecord) => void;
    deleteDisciplineRecord?: (recordId: string, employeeId: string) => Promise<void>;
    cancelDisciplineEdit?: () => void;
    applyJanusAccess?: () => void;
    toggleOffboardingTask?: (taskId: string, isComplete: boolean) => Promise<void>;
    createDefaultOffboardingTasks?: (employeeId: string) => Promise<void>;
    loadPerformanceReviewSupervisorNotify?: () => Promise<void>;
    refreshEmployeeDrawer?: () => Promise<void>;
    deleteEmployeeRecord?: () => Promise<void>;
    selectedEmployeeId?: string | null;
    cancelReviewEdit?: () => void;
    saveReviewRecord?: () => Promise<void>;
    saveEmployeeReview?: () => Promise<void>;
    editReviewRecord?: (review: ReviewRecord) => void;
    deleteReviewRecord?: (reviewId: string, employeeId: string) => Promise<void>;
    employeeDisplayName?: (employee?: Record<string, unknown> | null) => string;
    uploadEmployeeDocument?: () => Promise<void>;
    deleteEmployeeDocument?: (docId: string) => Promise<void>;
    loadPerformanceReviewAttachments?: (employeeId: string) => Promise<void>;
    uploadPerformanceReviewAttachment?: () => Promise<void>;
    signIn?: typeof signIn;
    registerAccount?: typeof registerAccount;
    setAuthMode?: typeof setAuthMode;
    signOut?: typeof signOut;
    showAuthenticatedOrbisView?: () => void;
    showAuthView?: () => void;
    bootstrapOrbisAfterAuth?: () => Promise<void>;
    clearOrbisSessionState?: () => void;
    getUserRole?: () => Promise<string | null>;
    isSignInFlowActive?: () => boolean;
    logManualPayrollHandoff?: () => Promise<void>;
    currentUserEmail?: string;
    currentUserRole?: string;
    buildEmployeeChangeLog?: (oldEmployee: Record<string, unknown>, newEmployee: Record<string, unknown>) => string;
    recordAuditEvent?: ( action: string, employee: Record<string, unknown> | null | undefined, details?: string ) => void | Promise<void>;
    cleanEmployeeNameValue?: (value: unknown) => string;
    isActiveDashboardEmployee?: (employee: Record<string, unknown>) => boolean;
    isInHouseFteEmployee?: ( employee: EmployeeLike | null | undefined ) => boolean;
    countInHouseFteEmployees?: (employees: EmployeeLike[]) => number;
    daysUntilDate?: ( dateValue: unknown ) => number | null;
    currentUserAccess?: UserAccessRow | null;
    isAdminUser?: () => boolean;
    canManageEmployeeRecords?: () => boolean;
    isSupervisorUser?: () => boolean;
    canEditEmployeeAdmin?: (employee?: EmployeeLike | null) => boolean;
    canAdjustPtoBalance?: () => boolean;
    employeeMatchesSupervisorAccess?: (employee: EmployeeLike) => boolean;
    applyAdminDashboardView?: () => void;
    applySupervisorDashboardView?: () => void;
    updateTopbarSignedInLabel?: (fallbackEmail?: string) => void;
    resolveSignedInUserLabel?: ( access?: UserAccessRow | null, fallbackEmail?: string ) => string;
    applyRoleLocks?: () => void;
    applyAddEmployeeAsCandidateAccess?: () => void;
    applyEmployeePortalView?: () => void;
    applyRoleNavigation?: () => void;
    canAccessOrbisApp?: () => boolean;
    canAccessAppSection?: (sectionId: string) => boolean;
    isEmployeeUser?: () => boolean;
    getLinkedEmployeeId?: () => string;
    generateAvailableEmployeeId?: () => Promise<string>;
    normalizeEmployee?: ( employee: NormalizableEmployee | null | undefined ) => NormalizedEmployee | null;

    loadDocuments?: () => Promise<void> | void;
    rosterViewMode?: string;
    refreshPerformanceReviewsDueKpi?: () => void | Promise<void>;
    deleteLeaveRequestById?: (requestId: string) => void | Promise<void>;
    exportOperationsIssuesCsv?: () => void;

    // Employee roster + audit bridge
    currentUser?: { email?: string; name?: string } | null;
    OrbisServices?: {
      employees?: {
        delete?: (id: string) => Promise<{ error?: { message?: string } | null }>;
        getAll?: () => Promise<{ data?: Record<string, unknown>[] }>;
      };
    };
    __suppressAuditDirty?: boolean;
    __employeeDirtyFields?: Set<string>;
    __employeeOriginalAuditSnapshot?: Record<string, unknown>;
    __employeeAdminDirtyBind?: boolean;
    __employeeAdminDirtyTrackingBound?: boolean;
    __employeeUpdateToastBind?: boolean;
    __employeeUpdateToastPending?: boolean;
    __employeeBeforeUpdate?: Record<string, unknown>;
    __employeeAdminBind?: boolean;
    __employeeAdminAuditBaseline?: Record<string, unknown>;
    refreshEmployeeRoster?: () => Promise<void>;
    clearFilters?: () => void;
    cleanRosterEmployeeNameValue?: (value: unknown) => string;
    formatRosterStatus?: (status: unknown) => string;
    normalizeEmployeeForRoster?: (employee: Record<string, unknown>) => Record<string, unknown>;
    getEmployeePublicId?: (employee: Record<string, unknown>, fallbackName?: string) => string;
    populateEmployeeAdminFallback?: (employee: Record<string, unknown>) => void;
    populateEmployeeAdminByVisibleOrder?: (employee: Record<string, unknown>) => void;
    getEmployeeSnapshotFromRosterRow?: (employeeId: string) => Record<string, unknown>;
    getFilteredRosterEmployees?: () => Record<string, unknown>[];
    openDrawerByEmployeeId?: (employeeId: string) => Promise<void>;
    deleteEmployeeQuick?: (employeeId: string) => void | Promise<void>;
    bindRosterEvents?: () => void;
    unlockRosterSearchInput?: () => void;
    ensureRosterViewTabs?: () => void;
    lockEmployeeIdField?: (field?: HTMLInputElement) => void;
    bindEmployeeUpdateToast?: () => void;
    getEmployeeAdminFormSnapshot?: () => Record<string, unknown>;
    getEmployeeAdminFieldByLabel?: (labelText: string) => HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | null;
    setEmployeeAdminAuditBaseline?: (snapshot?: Record<string, unknown>) => void;
    getEmployeeAdminAuditBaseline?: () => Record<string, unknown>;
    getEmployeeAdminFieldKey?: ((field: Element | null) => string) | ((label?: string) => string);
    bindEmployeeAdminDirtyTracking?: () => void;
    cleanEmployeeAdminVisibleNameFields?: () => void;
    getMeaningfulEmployeeAuditChanges?: (
      before: Record<string, unknown>,
      after: Record<string, unknown>
    ) => string[];
    getAuditLog?: () => unknown[];
    writeEmployeeAuditLogToSupabase?: (entry: Record<string, unknown>) => Promise<{ error?: unknown }>;
    writeEmployeeAuditLogLocal?: (entry: Record<string, unknown>) => void;
    fetchEmployeeAuditLogs?: (employeeId: string) => Promise<unknown[]>;
    getLocalAuditLogsForEmployee?: (employeeId: string) => unknown[];
    renderEmployeeAuditLogViewer?: (employee?: Record<string, unknown> | null) => void | Promise<void>;
    bindAtRiskKpiHover?: () => void;
  }
}
