-- Orbis core schema baseline for fresh Supabase projects (training / white-label).
-- BTW production already had these tables before the migration chain began.
-- Do not run on BTW production if tables already exist (IF NOT EXISTS is safe).

create extension if not exists "uuid-ossp" with schema extensions;

create table if not exists public.employees (
  "id" text NOT NULL,
  "first_name" text,
  "last_name" text,
  "department" text,
  "position" text,
  "supervisor" text,
  "hire_date" date,
  "status" text,
  "pay_type" text,
  "standard_hours" numeric,
  "review_cycle_months" numeric,
  "last_review_date" date,
  "next_review_date" date,
  "tenure_months" numeric,
  "tenure_years" numeric,
  "benefits_status" text,
  "anniversary_date" date,
  "work_email" text,
  "personal_email" text,
  "phone" text,
  "notes" text,
  "tenure_bracket" text,
  "review_due_soon" text,
  "rehire_eligible" boolean DEFAULT true,
  "termination_date" date,
  "termination_reason" text,
  "is_remote" boolean DEFAULT false,
  "pto_balance_hours" numeric,
  "pto_balance_as_of" date,
  primary key ("id")
);

create table if not exists public.user_access (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "email" text NOT NULL,
  "display_name" text NOT NULL,
  "role" text NOT NULL DEFAULT 'supervisor'::text,
  "supervisor_name" text NOT NULL,
  "can_delete" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "supervised_employee_ids" text[],
  "linked_employee_id" text,
  "approval_status" text NOT NULL DEFAULT 'pending'::text,
  "janus_access" boolean NOT NULL DEFAULT false,
  primary key ("id"),
  unique ("email")
);

create table if not exists public.profiles (
  "id" uuid,
  "email" text,
  "hr_role" text DEFAULT 'user'::text,
  primary key ("id")
);

create table if not exists public.job_requisitions (
  "id" uuid DEFAULT gen_random_uuid(),
  "title" text,
  "department" text,
  "hiring_manager" text,
  "employment_type" text,
  "location" text,
  "status" text DEFAULT 'Open'::text,
  "opened_date" date DEFAULT CURRENT_DATE,
  "target_start_date" date,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.candidates (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "requisition_id" uuid,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "email" text,
  "phone" text,
  "source" text,
  "stage" text DEFAULT 'Applied'::text,
  "applied_date" date DEFAULT CURRENT_DATE,
  "resume_url" text,
  "disposition_reason" text,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  "department" text,
  "position" text,
  "interview_date" date,
  "interview_time" time without time zone,
  "interview_type" text,
  "interview_status" text DEFAULT 'Not Scheduled'::text,
  "interview_notes" text,
  "offer_status" text DEFAULT 'Not Started'::text,
  "offer_amount" text,
  "target_start_date" date,
  "offer_date" date,
  "offer_notes" text,
  "resume_status" text DEFAULT 'Not Received'::text,
  "application_status" text DEFAULT 'Not Started'::text,
  "background_status" text DEFAULT 'Not Started'::text,
  "eligibility_status" text DEFAULT 'Not Started'::text,
  "document_notes" text,
  "linked_employee_id" text,
  primary key ("id")
);

create table if not exists public.separation_log (
  "id" bigint generated by default as identity,
  "employee" text,
  "last_day_worked" date,
  "status_change_date" date,
  "separation_type" text,
  "reason" text,
  "eligible_for_rehire" text,
  "final_pay_date" date,
  "exit_interview_completed" text,
  "notes" text,
  "employee_id_if_available" text,
  primary key ("id")
);

create table if not exists public.employee_notes (
  "id" bigint generated always as identity,
  "employee_id" text NOT NULL,
  "note_date" date NOT NULL DEFAULT CURRENT_DATE,
  "note_type" text,
  "note_text" text NOT NULL,
  "created_by" uuid,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.discipline_reports (
  "id" bigint generated always as identity,
  "employee_id" text NOT NULL,
  "incident_date" date NOT NULL DEFAULT CURRENT_DATE,
  "issue_type" text,
  "description" text NOT NULL,
  "action_taken" text,
  "report_status" text DEFAULT 'Open'::text,
  "follow_up_date" date,
  "created_by" uuid,
  "created_at" timestamptz DEFAULT now(),
  "discipline_level" text,
  "refused_to_sign" boolean DEFAULT false,
  "employee_signature" text,
  "manager_signature" text,
  "witness_signature" text,
  "date" date,
  "type" text,
  "status" text DEFAULT 'Open'::text,
  "level" text,
  primary key ("id")
);

create table if not exists public.employee_meetings (
  "id" bigint generated always as identity,
  "employee_id" text NOT NULL,
  "meeting_date" date DEFAULT CURRENT_DATE,
  "meeting_type" text,
  "subject" text,
  "notes" text,
  "follow_up_date" date,
  "created_by" uuid,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.emergency_contacts (
  "id" bigint generated by default as identity,
  "created_at" timestamptz DEFAULT now(),
  "employee_id" text,
  "contact_name" text,
  "relationship" text,
  "phone" text,
  "alternate_phone" text,
  "notes" text,
  "priority_order" integer DEFAULT 1,
  primary key ("id")
);

create table if not exists public.employee_documents (
  "id" bigint generated by default as identity,
  "employee_id" text NOT NULL,
  "document_type" text,
  "file_url" text,
  "file_name" text,
  "uploaded_at" timestamptz,
  "uploaded_by" uuid DEFAULT gen_random_uuid(),
  "file_ext" text,
  "file_path" text,
  "review_id" uuid,
  primary key ("id")
);

create table if not exists public.employee_reviews (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "employee_id" text NOT NULL,
  "review_date" date NOT NULL,
  "review_type" text,
  "attendance_score" integer,
  "performance_score" integer,
  "teamwork_score" integer,
  "attitude_score" integer,
  "reliability_score" integer,
  "strengths" text,
  "improvements" text,
  "employee_comments" text,
  "manager_comments" text,
  "overall_result" text,
  "created_by" uuid,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "refused_to_sign" boolean DEFAULT false,
  "quality_score" numeric,
  "communication_score" numeric,
  "judgement_score" numeric,
  "initiative_score" numeric,
  "knowledge_score" numeric,
  "training_score" numeric,
  "employee_signature" text,
  "manager_signature" text,
  "witness_signature" text,
  primary key ("id")
);

create table if not exists public.incident_reports (
  "id" uuid DEFAULT extensions.uuid_generate_v4(),
  "employee_id" text,
  "incident_date" date,
  "incident_type" text,
  "location" text,
  "description" text,
  "follow_up" text,
  "status" text DEFAULT 'Open'::text,
  "created_at" timestamp without time zone DEFAULT now(),
  "refused_to_sign" boolean DEFAULT false,
  "employee_signature" text,
  "manager_signature" text,
  "witness_signature" text,
  primary key ("id")
);

create table if not exists public.stay_interviews (
  "id" uuid DEFAULT gen_random_uuid(),
  "employee_id" text,
  "interview_date" date,
  "interview_type" text,
  "q1" text,
  "q2" text,
  "q3" text,
  "q4" text,
  "q5" text,
  "q6" text,
  "q7" text,
  "manager_summary" text,
  "created_at" timestamp without time zone DEFAULT now(),
  primary key ("id")
);

create table if not exists public.iron_shift_awards (
  "id" uuid DEFAULT extensions.uuid_generate_v4(),
  "employee_id" text,
  "award_date" date,
  "reason" text,
  "created_at" timestamp without time zone DEFAULT now(),
  primary key ("id")
);

create table if not exists public.candidate_interviews (
  "id" uuid DEFAULT gen_random_uuid(),
  "candidate_id" uuid,
  "interview_date" date,
  "interview_type" text,
  "interviewer" text,
  "feedback" text,
  "recommendation" text,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.candidate_offers (
  "id" uuid DEFAULT gen_random_uuid(),
  "candidate_id" uuid,
  "position_title" text,
  "pay_rate" numeric,
  "pay_type" text DEFAULT 'Hourly'::text,
  "schedule" text,
  "start_date" date,
  "offer_date" date DEFAULT CURRENT_DATE,
  "intro_period_days" integer DEFAULT 90,
  "benefits_summary" text,
  "pto_summary" text,
  "status" text DEFAULT 'Draft'::text,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.onboarding_checklists (
  "id" uuid DEFAULT gen_random_uuid(),
  "employee_id" text,
  "signed_date" date,
  "document_url" text,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.onboarding_templates (
  "id" uuid DEFAULT gen_random_uuid(),
  "code" text,
  "item_name" text,
  "required" boolean DEFAULT true,
  "sort_order" integer,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.onboarding_checklist_items (
  "id" uuid DEFAULT gen_random_uuid(),
  "employee_id" text,
  "template_id" uuid,
  "status" text DEFAULT 'Pending'::text,
  "signed_at" timestamptz,
  "document_url" text,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  primary key ("id")
);

create table if not exists public.onboarding_tasks (
  "id" uuid DEFAULT gen_random_uuid(),
  "employee_id" text,
  "task_name" text,
  "task_type" text,
  "section" text,
  "status" text DEFAULT 'Pending'::text,
  "due_date" date,
  "completed_at" timestamp without time zone,
  "completed_by" text,
  "notes" text,
  "created_at" timestamp without time zone DEFAULT now(),
  "show_in_portal" boolean DEFAULT true,
  "assigned_to" text DEFAULT 'hr'::text,
  "reminder_sent_at" timestamptz,
  primary key ("id")
);

create table if not exists public.onboarding_task_templates (
  "id" uuid DEFAULT gen_random_uuid(),
  "task_name" text,
  "task_type" text,
  "section" text,
  "default_due_days" integer,
  primary key ("id")
);

create table if not exists public.department (
  "id" bigint generated by default as identity,
  "created_at" timestamptz DEFAULT now(),
  "department" text,
  primary key ("id")
);

create table if not exists public.employee_audit_logs (
  "id" uuid DEFAULT gen_random_uuid(),
  "employee_id" text,
  "employee_name" text,
  "action_type" text,
  "fields_changed" jsonb,
  "changed_at" timestamptz DEFAULT now(),
  "changed_by" text,
  "metadata" jsonb,
  primary key ("id")
);

create table if not exists public.document_library (
  "id" uuid DEFAULT gen_random_uuid(),
  "title" text,
  "category" text,
  "description" text,
  "file_url" text,
  "version" text,
  "language" text DEFAULT 'English'::text,
  "effective_date" date,
  "is_active" boolean DEFAULT true,
  "uploaded_by" text,
  "created_at" timestamptz DEFAULT now(),
  "file_name" text,
  primary key ("id")
);

-- Foreign keys (candidate_notes FK added in 20250520120000)
alter table public.candidates drop constraint if exists candidates_requisition_id_fkey;
alter table public.candidates add constraint candidates_requisition_id_fkey foreign key (requisition_id) references public.job_requisitions(id);

alter table public.employee_notes drop constraint if exists employee_notes_employee_id_fkey;
alter table public.employee_notes add constraint employee_notes_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.discipline_reports drop constraint if exists discipline_reports_employee_id_fkey;
alter table public.discipline_reports add constraint discipline_reports_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.employee_meetings drop constraint if exists employee_meetings_employee_id_fkey;
alter table public.employee_meetings add constraint employee_meetings_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.employee_documents drop constraint if exists employee_documents_employee_id_fkey;
alter table public.employee_documents add constraint employee_documents_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.employee_documents drop constraint if exists employee_documents_review_id_fkey;
alter table public.employee_documents add constraint employee_documents_review_id_fkey foreign key (review_id) references public.employee_reviews(id);

alter table public.employee_reviews drop constraint if exists employee_reviews_employee_id_fkey;
alter table public.employee_reviews add constraint employee_reviews_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.incident_reports drop constraint if exists incident_reports_employee_id_fkey;
alter table public.incident_reports add constraint incident_reports_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.stay_interviews drop constraint if exists stay_interviews_employee_id_fkey;
alter table public.stay_interviews add constraint stay_interviews_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.candidate_interviews drop constraint if exists candidate_interviews_candidate_id_fkey;
alter table public.candidate_interviews add constraint candidate_interviews_candidate_id_fkey foreign key (candidate_id) references public.candidates(id);

alter table public.candidate_offers drop constraint if exists candidate_offers_candidate_id_fkey;
alter table public.candidate_offers add constraint candidate_offers_candidate_id_fkey foreign key (candidate_id) references public.candidates(id);

alter table public.onboarding_checklists drop constraint if exists onboarding_checklists_employee_id_fkey;
alter table public.onboarding_checklists add constraint onboarding_checklists_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.onboarding_checklist_items drop constraint if exists onboarding_checklist_items_employee_id_fkey;
alter table public.onboarding_checklist_items add constraint onboarding_checklist_items_employee_id_fkey foreign key (employee_id) references public.employees(id);

alter table public.onboarding_checklist_items drop constraint if exists onboarding_checklist_items_template_id_fkey;
alter table public.onboarding_checklist_items add constraint onboarding_checklist_items_template_id_fkey foreign key (template_id) references public.onboarding_templates(id);
